"$schema" = "https://starship.rs/config-schema.json"

# Only show directory + prompt symbol
format = """
$directory
$character
"""

# ---------------- DIRECTORY ----------------
[directory]
style = "fg:#E6E3DE"
format = "$path"
truncation_length = 3
truncation_symbol = "…/"

# ---------------- PROMPT CHARACTER ----------------
[character]
success_symbol = "[❯](fg:#B07A78)"
error_symbol   = "[❯](fg:#CFA3A0)"
